name: Run static analysis with Google C++ Analyzer
on: [push]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Google C++ Analyzer
        uses: naivesystems/googlecpp@5411f5553462324b5875d409bfac7699510b8e26
