name: Run static analysis with Google C++ Analyzer
on: [push]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull private package
        run: docker pull ghcr.io/naivesystems/googlecpp:v0.1.2

      - name: Run Google C++ Analyzer
        uses: ./action
