name: Run static analysis with Google C++ Analyzer
on: [push]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Google C++ Analyzer
        uses: naivesystems/googlecpp@f024dca79b5d34e03a15bba13b2c1877d2690524
