name: Run static analysis with Google C++ Analyzer
on: [pull_request]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Google C++ Analyzer
        uses: naivesystems/googlecpp@d556056dd8c86a3677490bcb31b3e67e26942811
